import type { StoreItem } from './store.types';

export const CURATED_STORE_ITEMS: StoreItem[] = [
  // ── 聊天助手 ──────────────────────────────────────────────
  {
    id: 'chatgpt',
    type: 'tool',
    source: 'curated',
    name: 'ChatGPT',
    description: 'OpenAI 的对话式 AI 助手，支持多轮对话、代码生成、文本创作。',
    url: 'https://chatgpt.com',
    iconText: '🤖',
    rating: 4.9,
    usersText: '100M+',
    pricing: 'freemium',
    featured: true,
    categories: ['聊天助手'],
    tags: ['对话', 'GPT-4', '免费试用'],
    links: [{ label: '访问', url: 'https://chatgpt.com' }],
    trialNotesMarkdown: '适合日常问答、写作与代码辅助。建议结合清晰的需求描述与示例输入。',
    recommendReasons: ['生态成熟，上手快', '多场景覆盖（写作/代码/分析）'],
    usageExamples: [
      '帮我写一封向老板请假的邮件，语气正式，理由是家中有事需处理两天',
      '用 Python 写一个爬取豆瓣电影 Top250 的脚本，保存为 CSV',
      '我有一段英文论文摘要，请翻译成中文并润色，保持学术风格',
    ],
    evalScore: { context: 90, creativity: 85, quality: 88, multimodal: 82, safety: 80, grade: 'S' },
  },
  {
    id: 'claude',
    type: 'tool',
    source: 'curated',
    name: 'Claude',
    description: 'Anthropic 的 AI 助手，擅长长文本理解、代码分析与创意写作，安全对齐做得最好。',
    url: 'https://claude.ai',
    iconText: '🧠',
    rating: 4.8,
    usersText: '50M+',
    pricing: 'freemium',
    featured: true,
    categories: ['聊天助手'],
    tags: ['对话', '长上下文', '安全'],
    links: [{ label: '访问', url: 'https://claude.ai' }],
    trialNotesMarkdown: '长文档总结与写作润色体验较好，适合做阅读理解与结构化输出。',
    recommendReasons: ['长文本能力突出', '输出风格稳定'],
    usageExamples: [
      '请阅读这份 50 页的年度报告 PDF，提取关键财务指标并生成摘要',
      '帮我把这段代码从 JavaScript 重构为 TypeScript，保留所有注释',
      '根据以下大纲，写一篇 2000 字的科技博客，结构清晰、论据充分',
    ],
    evalScore: { context: 95, creativity: 82, quality: 92, multimodal: 70, safety: 95, grade: 'S' },
  },
  {
    id: 'gemini',
    type: 'tool',
    source: 'curated',
    name: 'Gemini',
    description: 'Google 的多模态 AI 助手，深度集成 Google 全家桶（搜索、Docs、邮件等）。',
    url: 'https://gemini.google.com',
    iconText: '✨',
    rating: 4.7,
    usersText: '50M+',
    pricing: 'freemium',
    featured: false,
    categories: ['聊天助手'],
    tags: ['多模态', 'Google', 'Workspace'],
    links: [{ label: '访问', url: 'https://gemini.google.com' }],
    trialNotesMarkdown: '与 Google Workspace 配合效果最佳，可直接读取 Gmail、Docs 等内容。',
    recommendReasons: ['Google 生态深度集成', '图像理解能力强'],
    usageExamples: [
      '帮我总结 Gmail 里上周所有未读邮件的重点内容',
      '分析这张产品设计图，指出可能的用户体验问题',
      '根据我 Google Docs 中的会议纪要，生成一份行动计划',
    ],
    evalScore: { context: 85, creativity: 78, quality: 82, multimodal: 90, safety: 82, grade: 'A' },
  },
  {
    id: 'meta-ai',
    type: 'tool',
    source: 'curated',
    name: 'Meta AI',
    description: 'Meta 出品的免费 AI 助手，基于 Llama 模型，全功能免费，WhatsApp/Instagram 原生集成。',
    url: 'https://www.meta.ai',
    iconText: '🌐',
    rating: 4.4,
    usersText: '30M+',
    pricing: 'free',
    featured: false,
    categories: ['聊天助手'],
    tags: ['对话', 'Llama', '免费'],
    links: [{ label: '访问', url: 'https://www.meta.ai' }],
    recommendReasons: ['完全免费', 'Meta 社交平台原生集成'],
    usageExamples: [
      '在 WhatsApp 群聊中 @Meta AI 快速翻译一段外语消息',
      '用自然语言描述场景，让 Meta AI 在聊天中生成创意图片',
    ],
    evalScore: { context: 72, creativity: 70, quality: 72, multimodal: 65, safety: 75, grade: 'B' },
  },
  {
    id: 'mistral',
    type: 'tool',
    source: 'curated',
    name: 'Mistral AI',
    description: '法国 AI 公司出品，Le Chat 对话平台全球可访问，以高效率小模型与隐私保护著称。',
    url: 'https://chat.mistral.ai',
    iconText: '🌬️',
    rating: 4.5,
    usersText: '5M+',
    pricing: 'freemium',
    featured: false,
    categories: ['聊天助手'],
    tags: ['欧洲', '隐私', '高效'],
    links: [{ label: '访问', url: 'https://chat.mistral.ai' }],
    recommendReasons: ['欧洲隐私合规', '小模型推理效率高'],
    usageExamples: [
      '用 Le Chat 快速生成一份 GDPR 合规的隐私政策模板',
      '上传代码文件，让 Mistral 做 code review 并给出优化建议',
    ],
    evalScore: { context: 80, creativity: 75, quality: 80, multimodal: 55, safety: 82, grade: 'B' },
  },

  // ── 图像生成 ──────────────────────────────────────────────
  {
    id: 'midjourney',
    type: 'tool',
    source: 'curated',
    name: 'Midjourney',
    description: '顶级 AI 图像生成工具，适合设计灵感与风格探索，美术质量业界标杆。',
    url: 'https://www.midjourney.com',
    iconText: '🎨',
    rating: 4.9,
    usersText: '16M+',
    pricing: 'paid',
    featured: true,
    categories: ['图像生成'],
    tags: ['图像生成', '艺术', 'Discord'],
    links: [{ label: '访问', url: 'https://www.midjourney.com' }],
    trialNotesMarkdown: '建议从风格关键词入手，逐步增加细节约束（镜头、光线、材质等）。',
    recommendReasons: ['美术质量高', '风格表现力强'],
    evalScore: { context: 60, creativity: 98, quality: 95, multimodal: 85, safety: 75, grade: 'A' },
  },
  {
    id: 'dalle3',
    type: 'tool',
    source: 'curated',
    name: 'DALL-E 3',
    description: 'OpenAI 的图像生成模型，集成到 ChatGPT Plus，指令理解能力强，文字渲染准确。',
    url: 'https://openai.com/dall-e-3',
    iconText: '🖼️',
    rating: 4.7,
    usersText: '10M+',
    pricing: 'paid',
    featured: false,
    categories: ['图像生成'],
    tags: ['OpenAI', '文字渲染', '自然语言'],
    links: [{ label: '访问', url: 'https://openai.com/dall-e-3' }],
    recommendReasons: ['文字描述理解精准', '可通过 ChatGPT 直接使用'],
    evalScore: { context: 80, creativity: 85, quality: 88, multimodal: 80, safety: 85, grade: 'A' },
  },
  {
    id: 'adobe-firefly',
    type: 'tool',
    source: 'curated',
    name: 'Adobe Firefly',
    description: 'Adobe 出品的 AI 图像与矢量生成工具，专为创意工作者设计，商用无版权风险。',
    url: 'https://firefly.adobe.com',
    iconText: '🔥',
    rating: 4.5,
    usersText: '3M+',
    pricing: 'freemium',
    featured: false,
    categories: ['图像生成'],
    tags: ['Adobe', '商用', '无版权风险'],
    links: [{ label: '访问', url: 'https://firefly.adobe.com' }],
    recommendReasons: ['商用安全无版权争议', '与 Photoshop 深度集成'],
    evalScore: { context: 65, creativity: 80, quality: 82, multimodal: 75, safety: 92, grade: 'A' },
  },
  {
    id: 'ideogram',
    type: 'tool',
    source: 'curated',
    name: 'Ideogram',
    description: '以出色的文字渲染能力著称的 AI 图像工具，可生成带有精准文字的海报、封面设计。',
    url: 'https://ideogram.ai',
    iconText: '🖊️',
    rating: 4.6,
    usersText: '2M+',
    pricing: 'freemium',
    featured: false,
    categories: ['图像生成'],
    tags: ['文字渲染', '海报', '封面'],
    links: [{ label: '访问', url: 'https://ideogram.ai' }],
    recommendReasons: ['文字图像渲染最准确', '适合生成海报/Logo'],
    evalScore: { context: 70, creativity: 82, quality: 80, multimodal: 72, safety: 85, grade: 'A' },
  },
  {
    id: 'stable-diffusion',
    type: 'tool',
    source: 'github',
    name: 'Stable Diffusion',
    description: '最流行的开源图像生成模型，可本地部署，支持数千款社区微调模型（LoRA、Checkpoint）。',
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    iconText: '🌊',
    rating: 4.8,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['图像生成'],
    tags: ['开源', '本地部署', 'LoRA'],
    githubRepoUrl: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    links: [
      { label: 'GitHub', url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui' },
      { label: 'Civitai 模型', url: 'https://civitai.com' },
    ],
    recommendReasons: ['完全离线可用', '生态庞大社区模型丰富'],
    evalScore: { context: 55, creativity: 92, quality: 85, multimodal: 80, safety: 60, grade: 'B' },
  },

  // ── 代码开发 ──────────────────────────────────────────────
  {
    id: 'github-copilot',
    type: 'tool',
    source: 'curated',
    name: 'GitHub Copilot',
    description: 'AI 编码助手，支持代码补全与建议，适合多种语言与 IDE 集成。',
    url: 'https://github.com/features/copilot',
    iconText: '🧑‍💻',
    rating: 4.8,
    usersText: '1.8M+',
    pricing: 'paid',
    featured: false,
    categories: ['代码开发'],
    tags: ['代码补全', 'IDE 集成'],
    links: [{ label: '访问', url: 'https://github.com/features/copilot' }],
    evalScore: { context: 88, creativity: 60, quality: 85, multimodal: 40, safety: 85, grade: 'B' },
  },
  {
    id: 'cursor',
    type: 'tool',
    source: 'curated',
    name: 'Cursor',
    description: 'AI-first 代码编辑器，基于 VS Code 深度改造，支持代码库级别对话与自主修改。',
    url: 'https://cursor.sh',
    iconText: '⚡',
    rating: 4.9,
    usersText: '500K+',
    pricing: 'freemium',
    featured: true,
    categories: ['代码开发'],
    tags: ['AI 编辑器', '代码对话', 'VS Code'],
    links: [{ label: '访问', url: 'https://cursor.sh' }],
    trialNotesMarkdown: '⌘K 快捷内联修改，⌘L 对话侧边栏。开启 Cursor Rules 可固化项目规范。',
    recommendReasons: ['代码库级别理解能力强', '内联修改体验流畅'],
    evalScore: { context: 92, creativity: 65, quality: 90, multimodal: 45, safety: 82, grade: 'A' },
  },
  {
    id: 'codeium',
    type: 'tool',
    source: 'curated',
    name: 'Windsurf / Codeium',
    description: 'Codeium 出品的 AI 编码助手，提供免费代码补全插件，Windsurf 是新推出的 AI 编辑器。',
    url: 'https://codeium.com',
    iconText: '💨',
    rating: 4.6,
    usersText: '1M+',
    pricing: 'freemium',
    featured: false,
    categories: ['代码开发'],
    tags: ['免费', '代码补全', '多 IDE'],
    links: [{ label: '访问', url: 'https://codeium.com' }],
    recommendReasons: ['个人免费无限次', '支持 40+ IDE'],
    evalScore: { context: 80, creativity: 58, quality: 78, multimodal: 35, safety: 80, grade: 'B' },
  },
  {
    id: 'tabnine',
    type: 'tool',
    source: 'curated',
    name: 'Tabnine',
    description: '专注于隐私的 AI 代码补全工具，支持本地模型，适合对数据安全要求高的团队。',
    url: 'https://www.tabnine.com',
    iconText: '🔒',
    rating: 4.4,
    usersText: '1M+',
    pricing: 'freemium',
    featured: false,
    categories: ['代码开发'],
    tags: ['隐私优先', '本地模型', '企业'],
    links: [{ label: '访问', url: 'https://www.tabnine.com' }],
    recommendReasons: ['支持完全离线运行', '企业级数据隔离'],
    evalScore: { context: 72, creativity: 50, quality: 72, multimodal: 30, safety: 90, grade: 'B' },
  },
  {
    id: 'continue',
    type: 'tool',
    source: 'github',
    name: 'Continue.dev',
    description: '开源 AI 编码助手 VS Code/JetBrains 插件，可自由配置任意模型（本地或云端）。',
    url: 'https://github.com/continuedev/continue',
    iconText: '🔗',
    rating: 4.6,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['代码开发', '开发者工具'],
    tags: ['开源', '本地模型', 'VS Code'],
    githubRepoUrl: 'https://github.com/continuedev/continue',
    links: [
      { label: 'GitHub', url: 'https://github.com/continuedev/continue' },
      { label: '文档', url: 'https://docs.continue.dev' },
    ],
    recommendReasons: ['可接本地 Ollama/LM Studio', '完全掌控数据'],
    evalScore: { context: 78, creativity: 55, quality: 75, multimodal: 35, safety: 85, grade: 'B' },
  },
  {
    id: 'replit',
    type: 'tool',
    source: 'curated',
    name: 'Replit AI',
    description: '云端 IDE 内置 AI 能力，可通过对话直接构建和部署完整 Web 应用，无需本地环境配置。',
    url: 'https://replit.com',
    iconText: '🔄',
    rating: 4.5,
    usersText: '20M+',
    pricing: 'freemium',
    featured: false,
    categories: ['代码开发'],
    tags: ['云端 IDE', '部署', '快速原型'],
    links: [{ label: '访问', url: 'https://replit.com' }],
    recommendReasons: ['零环境配置', '一键部署应用'],
    evalScore: { context: 75, creativity: 65, quality: 75, multimodal: 50, safety: 78, grade: 'B' },
  },

  // ── 搜索与研究 ────────────────────────────────────────────
  {
    id: 'perplexity',
    type: 'tool',
    source: 'curated',
    name: 'Perplexity',
    description: 'AI 搜索引擎，实时联网搜索并给出可追溯来源的答案。',
    url: 'https://www.perplexity.ai',
    iconText: '🔎',
    rating: 4.7,
    usersText: '10M+',
    pricing: 'freemium',
    featured: true,
    categories: ['搜索与研究'],
    tags: ['联网', '引用'],
    links: [{ label: '访问', url: 'https://www.perplexity.ai' }],
    evalScore: { context: 88, creativity: 55, quality: 90, multimodal: 60, safety: 88, grade: 'A' },
  },
  {
    id: 'you-com',
    type: 'tool',
    source: 'curated',
    name: 'You.com',
    description: 'AI 搜索引擎，集成多个顶尖模型（GPT-4、Claude、Gemini），支持联网与文件上传。',
    url: 'https://you.com',
    iconText: '🧭',
    rating: 4.4,
    usersText: '3M+',
    pricing: 'freemium',
    featured: false,
    categories: ['搜索与研究'],
    tags: ['多模型', '联网', '文件上传'],
    links: [{ label: '访问', url: 'https://you.com' }],
    recommendReasons: ['一处切换多个 AI 模型', '研究任务内置工具多'],
    evalScore: { context: 78, creativity: 55, quality: 75, multimodal: 60, safety: 80, grade: 'B' },
  },
  {
    id: 'phind',
    type: 'tool',
    source: 'curated',
    name: 'Phind',
    description: '专为开发者打造的 AI 搜索引擎，擅长代码问题解答，联网实时获取最新技术文档。',
    url: 'https://www.phind.com',
    iconText: '🔬',
    rating: 4.5,
    usersText: '1M+',
    pricing: 'freemium',
    featured: false,
    categories: ['搜索与研究', '代码开发'],
    tags: ['开发者', '技术文档', '联网'],
    links: [{ label: '访问', url: 'https://www.phind.com' }],
    recommendReasons: ['技术问题解答专业', '联网抓取最新文档'],
    evalScore: { context: 85, creativity: 50, quality: 82, multimodal: 40, safety: 82, grade: 'B' },
  },
  {
    id: 'tavily',
    type: 'tool',
    source: 'curated',
    name: 'Tavily',
    description: '专为 AI Agent 设计的搜索 API，返回干净的 Markdown 结构化结果，RAG/Agent 场景首选。',
    url: 'https://tavily.com',
    iconText: '🕹️',
    rating: 4.5,
    usersText: '50K+',
    pricing: 'freemium',
    featured: false,
    categories: ['搜索与研究', '开发者工具'],
    tags: ['API', 'Agent', 'RAG', '联网'],
    links: [{ label: '访问', url: 'https://tavily.com' }],
    recommendReasons: ['专为 AI Agent 优化', '返回结构化 Markdown'],
    evalScore: { context: 70, creativity: 40, quality: 80, multimodal: 35, safety: 85, grade: 'B' },
  },
  {
    id: 'firecrawl',
    type: 'tool',
    source: 'github',
    name: 'Firecrawl',
    description: '开源网页抓取/解析工具，便于把网页内容变成可用的数据。',
    url: 'https://github.com/mendableai/firecrawl',
    iconText: '🕸️',
    rating: 4.5,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['开发者工具', '数据'],
    tags: ['GitHub', '爬虫', '解析'],
    githubRepoUrl: 'https://github.com/mendableai/firecrawl',
    links: [{ label: 'GitHub', url: 'https://github.com/mendableai/firecrawl' }],
    trialNotesMarkdown: '适合做网页内容采集与结构化，后续可接入向量库/RAG。',
    recommendReasons: ['开源可自部署', '易于接入数据管道'],
    evalScore: { context: 55, creativity: 35, quality: 78, multimodal: 40, safety: 80, grade: 'C' },
  },

  // ── 写作内容 ──────────────────────────────────────────────
  {
    id: 'notion-ai',
    type: 'tool',
    source: 'curated',
    name: 'Notion AI',
    description: '在 Notion 中直接使用 AI 进行写作、总结、改写与结构化整理。',
    url: 'https://www.notion.so/product/ai',
    iconText: '📝',
    rating: 4.6,
    usersText: '10M+',
    pricing: 'paid',
    featured: false,
    categories: ['写作内容', '效率工具'],
    tags: ['写作', '总结', '知识库'],
    links: [{ label: '访问', url: 'https://www.notion.so/product/ai' }],
    evalScore: { context: 80, creativity: 75, quality: 80, multimodal: 55, safety: 85, grade: 'A' },
  },
  {
    id: 'jasper',
    type: 'tool',
    source: 'curated',
    name: 'Jasper',
    description: '专注营销写作的 AI 工具，提供博客、广告、邮件等场景模板，支持品牌声音定制。',
    url: 'https://www.jasper.ai',
    iconText: '✍️',
    rating: 4.4,
    usersText: '100K+',
    pricing: 'paid',
    featured: false,
    categories: ['写作内容'],
    tags: ['营销', '博客', '品牌'],
    links: [{ label: '访问', url: 'https://www.jasper.ai' }],
    recommendReasons: ['营销文案场景覆盖全', '品牌声音一致性好'],
    evalScore: { context: 72, creativity: 85, quality: 78, multimodal: 45, safety: 80, grade: 'B' },
  },
  {
    id: 'copy-ai',
    type: 'tool',
    source: 'curated',
    name: 'Copy.ai',
    description: '一键生成营销文案、社交媒体帖子、产品描述，适合中小团队快速产出内容。',
    url: 'https://www.copy.ai',
    iconText: '📋',
    rating: 4.3,
    usersText: '500K+',
    pricing: 'freemium',
    featured: false,
    categories: ['写作内容'],
    tags: ['文案', '社交媒体', '营销'],
    links: [{ label: '访问', url: 'https://www.copy.ai' }],
    recommendReasons: ['免费额度充足', '入门简单'],
    evalScore: { context: 65, creativity: 80, quality: 72, multimodal: 40, safety: 78, grade: 'B' },
  },
  {
    id: 'grammarly',
    type: 'tool',
    source: 'curated',
    name: 'Grammarly',
    description: 'AI 写作助手，专注英文语法修改、语气调整和清晰度改进，浏览器插件随处可用。',
    url: 'https://www.grammarly.com',
    iconText: '📗',
    rating: 4.7,
    usersText: '30M+',
    pricing: 'freemium',
    featured: false,
    categories: ['写作内容'],
    tags: ['英文', '语法', '润色'],
    links: [{ label: '访问', url: 'https://www.grammarly.com' }],
    recommendReasons: ['浏览器插件，随处可用', '英文写作必备'],
    evalScore: { context: 82, creativity: 55, quality: 90, multimodal: 35, safety: 92, grade: 'B' },
  },

  // ── 视频 & 音频 ───────────────────────────────────────────
  {
    id: 'runway',
    type: 'tool',
    source: 'curated',
    name: 'Runway',
    description: '专业 AI 视频生成与编辑工具，支持文本到视频、图像到视频。',
    url: 'https://runwayml.com',
    iconText: '🎬',
    rating: 4.7,
    usersText: '2M+',
    pricing: 'freemium',
    featured: false,
    categories: ['视频 & 音频'],
    tags: ['视频生成', '编辑'],
    links: [{ label: '访问', url: 'https://runwayml.com' }],
    evalScore: { context: 60, creativity: 90, quality: 85, multimodal: 95, safety: 78, grade: 'A' },
  },
  {
    id: 'elevenlabs',
    type: 'tool',
    source: 'curated',
    name: 'ElevenLabs',
    description: '顶级 AI 语音合成与克隆工具，支持 29 种语言，适合播客、有声书与视频配音。',
    url: 'https://elevenlabs.io',
    iconText: '🎙️',
    rating: 4.8,
    usersText: '1M+',
    pricing: 'freemium',
    featured: true,
    categories: ['视频 & 音频'],
    tags: ['语音合成', '声音克隆', '多语言'],
    links: [{ label: '访问', url: 'https://elevenlabs.io' }],
    trialNotesMarkdown: '免费版每月 1 万字符额度，语音克隆仅需 1 分钟音频样本。',
    recommendReasons: ['语音自然度业界最佳', '多语言效果好'],
    evalScore: { context: 55, creativity: 82, quality: 92, multimodal: 88, safety: 80, grade: 'A' },
  },
  {
    id: 'suno',
    type: 'tool',
    source: 'curated',
    name: 'Suno',
    description: 'AI 音乐生成工具，输入歌词或风格描述即可生成完整歌曲，包含人声与编曲。',
    url: 'https://suno.com',
    iconText: '🎵',
    rating: 4.7,
    usersText: '5M+',
    pricing: 'freemium',
    featured: false,
    categories: ['视频 & 音频'],
    tags: ['音乐生成', '歌曲', '人声'],
    links: [{ label: '访问', url: 'https://suno.com' }],
    recommendReasons: ['生成完整歌曲含人声', '风格多样'],
    evalScore: { context: 50, creativity: 92, quality: 82, multimodal: 85, safety: 75, grade: 'A' },
  },
  {
    id: 'heygen',
    type: 'tool',
    source: 'curated',
    name: 'HeyGen',
    description: 'AI 数字人视频生成平台，上传照片即可生成会说话的数字人视频，支持多语言配音。',
    url: 'https://www.heygen.com',
    iconText: '🎭',
    rating: 4.6,
    usersText: '500K+',
    pricing: 'freemium',
    featured: false,
    categories: ['视频 & 音频'],
    tags: ['数字人', '视频生成', '多语言'],
    links: [{ label: '访问', url: 'https://www.heygen.com' }],
    recommendReasons: ['无需录制，照片生成数字人', '翻译视频效果出色'],
    evalScore: { context: 55, creativity: 78, quality: 80, multimodal: 90, safety: 78, grade: 'A' },
  },

  // ── 效率工具 ──────────────────────────────────────────────
  {
    id: 'zapier',
    type: 'tool',
    source: 'curated',
    name: 'Zapier',
    description: 'AI 驱动的自动化平台，连接 6000+ 应用，无需代码实现工作流自动化。',
    url: 'https://zapier.com',
    iconText: '⚡',
    rating: 4.6,
    usersText: '2M+',
    pricing: 'freemium',
    featured: false,
    categories: ['效率工具'],
    tags: ['自动化', '无代码', 'Webhook'],
    links: [{ label: '访问', url: 'https://zapier.com' }],
    recommendReasons: ['无代码连接一切', '场景模板丰富'],
    evalScore: { context: 65, creativity: 50, quality: 78, multimodal: 45, safety: 85, grade: 'B' },
  },
  {
    id: 'n8n',
    type: 'tool',
    source: 'github',
    name: 'n8n',
    description: '开源工作流自动化平台，可自托管，支持代码节点与 AI Agent 编排，比 Zapier 更灵活。',
    url: 'https://n8n.io',
    iconText: '🔀',
    rating: 4.7,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['效率工具', '开发者工具'],
    tags: ['开源', '自动化', '自托管'],
    githubRepoUrl: 'https://github.com/n8n-io/n8n',
    links: [
      { label: '访问', url: 'https://n8n.io' },
      { label: 'GitHub', url: 'https://github.com/n8n-io/n8n' },
    ],
    recommendReasons: ['开源可完全自托管', '支持代码逻辑节点'],
    evalScore: { context: 68, creativity: 55, quality: 80, multimodal: 48, safety: 82, grade: 'B' },
  },
  {
    id: 'mem-ai',
    type: 'tool',
    source: 'curated',
    name: 'Mem',
    description: 'AI 笔记工具，自动整理和关联你的笔记，提供基于个人知识库的问答功能。',
    url: 'https://mem.ai',
    iconText: '🧩',
    rating: 4.3,
    usersText: '200K+',
    pricing: 'freemium',
    featured: false,
    categories: ['效率工具'],
    tags: ['笔记', '知识库', 'AI 问答'],
    links: [{ label: '访问', url: 'https://mem.ai' }],
    recommendReasons: ['笔记自动关联', '可对知识库问答'],
    evalScore: { context: 75, creativity: 55, quality: 72, multimodal: 40, safety: 80, grade: 'B' },
  },

  // ── 数据分析 ──────────────────────────────────────────────
  {
    id: 'julius-ai',
    type: 'tool',
    source: 'curated',
    name: 'Julius',
    description: '数据分析 AI，上传 Excel/CSV 文件后用自然语言进行分析、可视化和统计建模。',
    url: 'https://julius.ai',
    iconText: '📊',
    rating: 4.6,
    usersText: '200K+',
    pricing: 'freemium',
    featured: false,
    categories: ['数据分析'],
    tags: ['数据分析', 'Excel', '可视化'],
    links: [{ label: '访问', url: 'https://julius.ai' }],
    recommendReasons: ['零代码数据分析', 'Excel/CSV 直接上传'],
    evalScore: { context: 72, creativity: 50, quality: 82, multimodal: 65, safety: 82, grade: 'B' },
  },

  // ── 开发者工具/Agent 技能 ────────────────────────────────
  {
    id: 'langchain',
    type: 'skill',
    source: 'github',
    name: 'LangChain',
    description: '构建 LLM 应用的开源框架，覆盖链式调用、工具调用与 RAG 基础能力。',
    url: 'https://github.com/langchain-ai/langchain',
    iconText: '⛓️',
    rating: 4.6,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['Agent 技能', '开发者工具'],
    tags: ['GitHub', 'Agent', 'RAG'],
    githubRepoUrl: 'https://github.com/langchain-ai/langchain',
    links: [
      { label: 'GitHub', url: 'https://github.com/langchain-ai/langchain' },
      { label: '文档', url: 'https://python.langchain.com' },
    ],
    evalScore: { context: 75, creativity: 60, quality: 78, multimodal: 55, safety: 75, grade: 'B' },
  },
  {
    id: 'llamaindex',
    type: 'skill',
    source: 'github',
    name: 'LlamaIndex',
    description: '专为数据索引与 RAG 应用设计的 LLM 框架，数据连接器丰富，支持多种向量数据库。',
    url: 'https://github.com/run-llama/llama_index',
    iconText: '🦙',
    rating: 4.7,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['Agent 技能', '开发者工具'],
    tags: ['GitHub', 'RAG', '向量数据库'],
    githubRepoUrl: 'https://github.com/run-llama/llama_index',
    links: [
      { label: 'GitHub', url: 'https://github.com/run-llama/llama_index' },
      { label: '文档', url: 'https://docs.llamaindex.ai' },
    ],
    recommendReasons: ['RAG 场景生产级方案', '数据连接器最丰富'],
    evalScore: { context: 78, creativity: 50, quality: 82, multimodal: 55, safety: 80, grade: 'B' },
  },
  {
    id: 'dify',
    type: 'skill',
    source: 'github',
    name: 'Dify',
    description: '开源 LLM 应用开发平台，提供可视化编排界面，可快速构建 RAG 应用与 Agent 工作流。',
    url: 'https://dify.ai',
    iconText: '🧩',
    rating: 4.8,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: true,
    categories: ['Agent 技能', '开发者工具'],
    tags: ['GitHub', '可视化编排', '工作流'],
    githubRepoUrl: 'https://github.com/langgenius/dify',
    links: [
      { label: '访问', url: 'https://dify.ai' },
      { label: 'GitHub', url: 'https://github.com/langgenius/dify' },
    ],
    trialNotesMarkdown: '可视化 Workflow 最适合快速验证 Agent 逻辑；内置多种数据集格式支持。',
    recommendReasons: ['可视化编排降低门槛', '内置 RAG 数据管道'],
    evalScore: { context: 72, creativity: 65, quality: 80, multimodal: 55, safety: 82, grade: 'B' },
  },
  {
    id: 'flowise',
    type: 'skill',
    source: 'github',
    name: 'Flowise',
    description: '拖拽式 LLM Agent/Chain 构建工具，基于 LangChain，无需写代码即可搭建 AI 工作流。',
    url: 'https://flowiseai.com',
    iconText: '🌊',
    rating: 4.5,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['Agent 技能', '开发者工具'],
    tags: ['GitHub', '拖拽', 'LangChain'],
    githubRepoUrl: 'https://github.com/FlowiseAI/Flowise',
    links: [
      { label: '访问', url: 'https://flowiseai.com' },
      { label: 'GitHub', url: 'https://github.com/FlowiseAI/Flowise' },
    ],
    recommendReasons: ['无代码搭建 Agent 流', '部署简单可自托管'],
    evalScore: { context: 65, creativity: 60, quality: 72, multimodal: 45, safety: 78, grade: 'B' },
  },
  {
    id: 'crewai',
    type: 'skill',
    source: 'github',
    name: 'CrewAI',
    description: '多 Agent 协作框架，通过角色扮演让多个 AI Agent 分工合作完成复杂任务。',
    url: 'https://github.com/crewAIInc/crewAI',
    iconText: '👥',
    rating: 4.6,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['Agent 技能'],
    tags: ['GitHub', '多 Agent', '协作'],
    githubRepoUrl: 'https://github.com/crewAIInc/crewAI',
    links: [{ label: 'GitHub', url: 'https://github.com/crewAIInc/crewAI' }],
    recommendReasons: ['多 Agent 分工协作', '角色定义清晰直观'],
    evalScore: { context: 78, creativity: 70, quality: 75, multimodal: 40, safety: 75, grade: 'B' },
  },
  {
    id: 'ollama',
    type: 'tool',
    source: 'github',
    name: 'Ollama',
    description: '本地运行大模型的最简方案，一行命令下载并运行 Llama、Mistral、DeepSeek 等主流模型。',
    url: 'https://ollama.com',
    iconText: '🦙',
    rating: 4.8,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['开发者工具'],
    tags: ['本地模型', '隐私', '开源'],
    githubRepoUrl: 'https://github.com/ollama/ollama',
    links: [
      { label: '访问', url: 'https://ollama.com' },
      { label: 'GitHub', url: 'https://github.com/ollama/ollama' },
    ],
    trialNotesMarkdown: '```\nollama run llama3\n```\n支持 Mac/Linux/Windows，最简单的本地模型运行方式。',
    recommendReasons: ['一行命令运行本地大模型', '完全离线保护隐私'],
    evalScore: { context: 70, creativity: 60, quality: 78, multimodal: 55, safety: 85, grade: 'B' },
  },
];

export const DEFAULT_TOOL_CATEGORIES = [
  '聊天助手',
  '图像生成',
  '视频 & 音频',
  '代码开发',
  '写作内容',
  '数据分析',
  '效率工具',
  '搜索与研究',
  '开发者工具',
  '数据',
  'Agent 技能',
];
