import type { StoreItem } from './store.types';

export const CURATED_STORE_ITEMS: StoreItem[] = [
  {
    id: 'chatgpt',
    type: 'tool',
    source: 'curated',
    name: 'ChatGPT',
    description: 'OpenAI 的对话式 AI 助手，支持多轮对话、代码生成、文本创作。',
    url: 'https://chatgpt.com',
    iconText: '🤖',
    rating: 4.9,
    usersText: '100M+',
    pricing: 'freemium',
    featured: true,
    categories: ['聊天助手'],
    tags: ['对话', 'GPT-4', '免费试用'],
    links: [
      { label: '访问', url: 'https://chatgpt.com' },
    ],
    trialNotesMarkdown: '适合日常问答、写作与代码辅助。建议结合清晰的需求描述与示例输入。',
    recommendReasons: ['生态成熟，上手快', '多场景覆盖（写作/代码/分析）'],
  },
  {
    id: 'claude',
    type: 'tool',
    source: 'curated',
    name: 'Claude',
    description: 'Anthropic 的 AI 助手，擅长长文本理解、代码分析与创意写作。',
    url: 'https://claude.ai',
    iconText: '🧠',
    rating: 4.8,
    usersText: '50M+',
    pricing: 'freemium',
    featured: true,
    categories: ['聊天助手'],
    tags: ['对话', '长上下文'],
    links: [
      { label: '访问', url: 'https://claude.ai' },
    ],
    trialNotesMarkdown: '长文档总结与写作润色体验较好，适合做阅读理解与结构化输出。',
    recommendReasons: ['长文本能力突出', '输出风格稳定'],
  },
  {
    id: 'midjourney',
    type: 'tool',
    source: 'curated',
    name: 'Midjourney',
    description: '顶级 AI 图像生成工具，适合设计灵感与风格探索。',
    url: 'https://www.midjourney.com',
    iconText: '🎨',
    rating: 4.9,
    usersText: '16M+',
    pricing: 'paid',
    featured: true,
    categories: ['图像生成'],
    tags: ['图像生成', '艺术', 'Discord'],
    links: [
      { label: '访问', url: 'https://www.midjourney.com' },
    ],
    trialNotesMarkdown: '建议从风格关键词入手，逐步增加细节约束（镜头、光线、材质等）。',
    recommendReasons: ['美术质量高', '风格表现力强'],
  },
  {
    id: 'github-copilot',
    type: 'tool',
    source: 'curated',
    name: 'GitHub Copilot',
    description: 'AI 编码助手，支持代码补全与建议，适合多种语言与 IDE 集成。',
    url: 'https://github.com/features/copilot',
    iconText: '🧑‍💻',
    rating: 4.8,
    usersText: '1.8M+',
    pricing: 'paid',
    featured: false,
    categories: ['代码开发'],
    tags: ['代码补全', 'IDE 集成'],
    links: [
      { label: '访问', url: 'https://github.com/features/copilot' },
    ],
  },
  {
    id: 'perplexity',
    type: 'tool',
    source: 'curated',
    name: 'Perplexity',
    description: 'AI 搜索引擎，实时联网搜索并给出可追溯来源的答案。',
    url: 'https://www.perplexity.ai',
    iconText: '🔎',
    rating: 4.7,
    usersText: '10M+',
    pricing: 'freemium',
    featured: true,
    categories: ['搜索与研究'],
    tags: ['联网', '引用'],
    links: [
      { label: '访问', url: 'https://www.perplexity.ai' },
    ],
  },
  {
    id: 'runway',
    type: 'tool',
    source: 'curated',
    name: 'Runway',
    description: '专业 AI 视频生成与编辑工具，支持文本到视频、图像到视频。',
    url: 'https://runwayml.com',
    iconText: '🎬',
    rating: 4.7,
    usersText: '2M+',
    pricing: 'freemium',
    featured: false,
    categories: ['视频 & 音频'],
    tags: ['视频生成', '编辑'],
    links: [
      { label: '访问', url: 'https://runwayml.com' },
    ],
  },
  {
    id: 'notion-ai',
    type: 'tool',
    source: 'curated',
    name: 'Notion AI',
    description: '在 Notion 中直接使用 AI 进行写作、总结、改写与结构化整理。',
    url: 'https://www.notion.so/product/ai',
    iconText: '📝',
    rating: 4.6,
    usersText: '10M+',
    pricing: 'paid',
    featured: false,
    categories: ['写作内容', '效率工具'],
    tags: ['写作', '总结', '知识库'],
    links: [
      { label: '访问', url: 'https://www.notion.so/product/ai' },
    ],
  },
  {
    id: 'firecrawl',
    type: 'tool',
    source: 'github',
    name: 'Firecrawl',
    description: '开源网页抓取/解析工具，便于把网页内容变成可用的数据。',
    url: 'https://github.com/mendableai/firecrawl',
    iconText: '🕸️',
    rating: 4.5,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['开发者工具', '数据'],
    tags: ['GitHub', '爬虫', '解析'],
    githubRepoUrl: 'https://github.com/mendableai/firecrawl',
    links: [
      { label: 'GitHub', url: 'https://github.com/mendableai/firecrawl' },
    ],
    trialNotesMarkdown: '适合做网页内容采集与结构化，后续可接入向量库/RAG。',
    recommendReasons: ['开源可自部署', '易于接入数据管道'],
  },
  {
    id: 'langchain',
    type: 'skill',
    source: 'github',
    name: 'LangChain',
    description: '构建 LLM 应用的开源框架，覆盖链式调用、工具调用与 RAG 基础能力。',
    url: 'https://github.com/langchain-ai/langchain',
    iconText: '⛓️',
    rating: 4.6,
    usersText: 'GitHub',
    pricing: 'open_source',
    featured: false,
    categories: ['Agent 技能', '开发者工具'],
    tags: ['GitHub', 'Agent', 'RAG'],
    githubRepoUrl: 'https://github.com/langchain-ai/langchain',
    links: [
      { label: 'GitHub', url: 'https://github.com/langchain-ai/langchain' },
      { label: '文档', url: 'https://python.langchain.com' },
    ],
  },
];

export const DEFAULT_TOOL_CATEGORIES = [
  '聊天助手',
  '图像生成',
  '视频 & 音频',
  '代码开发',
  '写作内容',
  '数据分析',
  '效率工具',
  '搜索与研究',
  '开发者工具',
  '数据',
];

